In [1]:
import pandas as pd 
import numpy as np
import matplotlib
%matplotlib inline
import seaborn as sns 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import random
import warnings
warnings.filterwarnings('ignore')


In [2]:
pd.set_option('display.width', 5000)
data = pd.read_csv('C:\\Sohan\\ML_Acmegrade\\ML Day13 5\\pacific.csv')
data.head()


ID                 Name      Date  Time Event Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW
0  EP011949              UNNAMED  19490611     0           TS    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
1  EP011949              UNNAMED  19490611   600           TS    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
2  EP011949              UNNAMED  19490611  1200           TS    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
3  EP011949              UNNAMED  19490611  1800           TS    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
4  EP011949              UNNAMED  19490612     0           TS    20.4N    108.6W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999

[5 rows x 22 columns]

In [3]:
#dependent var(Y)
data.groupby('Status').agg({'Status': np.size})

Status
Status        
 DB        217
 ET        152
 EX        110
 HU       6766
 LO       1828
 PT          6
 SD          4
 SS          7
 ST          6
 TD       6965
 TS      10076

In [4]:
#label encoding with cat.codes ; 
data.Status = pd.Categorical(data.Status)
data['Status'] = data.Status.cat.codes
data.head()


ID                 Name      Date  Time Event  Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW
0  EP011949              UNNAMED  19490611     0            10    20.2N    106.3W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
1  EP011949              UNNAMED  19490611   600            10    20.2N    106.4W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
2  EP011949              UNNAMED  19490611  1200            10    20.2N    106.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
3  EP011949              UNNAMED  19490611  1800            10    20.3N    107.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
4  EP011949              UNNAMED  19490612     0            10    20.4N    108.6W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999

[5 rows x 22 columns]

In [5]:
data.groupby('Status').agg({'Status': np.size})

Status
Status        
0          217
1          152
2          110
3         6766
4         1828
5            6
6            4
7            7
8            6
9         6965
10       10076

In [6]:
random.seed(2)
pred_columns = data[:]
pred_columns.drop(['Status'],axis=1,inplace=True)#coz thats Y column
pred_columns.drop(['Event'],axis=1,inplace=True)#rest of these are unwanted data
pred_columns.drop(['Latitude'],axis=1,inplace=True)
pred_columns.drop(['Longitude'],axis=1,inplace=True)
pred_columns.drop(['ID'],axis=1,inplace=True)
pred_columns.drop(['Name'],axis=1,inplace=True)
pred_columns.drop(['Date'],axis=1,inplace=True)
pred_columns.drop(['Time'],axis=1,inplace=True)
prediction_var = pred_columns.columns
print(list(prediction_var))# my X column


['Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']


In [7]:
from sklearn.model_selection  import train_test_split
train, test = train_test_split(data, test_size = 0.3)
print(train.shape)
print(test.shape)
#here we did train to split for the whole data

(18295, 22)
(7842, 22)


In [8]:
train

ID                 Name      Date  Time Event  Status Latitude Longitude  Maximum Wind  Minimum Pressure  ...  Low Wind SW  Low Wind NW  Moderate Wind NE  Moderate Wind SE  Moderate Wind SW  Moderate Wind NW  High Wind NE  High Wind SE  High Wind SW  High Wind NW
17178  EP171997                 OLAF  19970927  1200            10    14.1N     94.8W            55               990  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
14959  EP041993               CALVIN  19930706  1200             3    15.4N    100.4W            85               972  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
3602   EP151968                 ORLA  19680927  1200            10    17.3N    126.7W            45              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
16227  EP061995                ERICK  19950804   600            10    16.2N    116.8W            35              1004  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
15700  CP011994              UNNAMED  19940809  1200             9    15.6N    145.8W            30              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
...         ...                  ...       ...   ...   ...     ...      ...       ...           ...               ...  ...          ...          ...               ...               ...               ...               ...           ...           ...           ...           ...
14385  EP111992               JAVIER  19920811     0             9    13.8N    154.1W            25              1009  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
21580  EP142007             JULIETTE  20070930     0            10    16.7N    112.2W            35              1003  ...           60           30                 0                 0                 0                 0             0             0             0             0
23020  EP092010                FRANK  20100823     0            10    14.0N     96.4W            50               998  ...           30           50                20                 0                 0                20             0             0             0             0
6523   EP071976                 GWEN  19760817     0             9    22.0N    152.0W            25              -999  ...         -999         -999              -999              -999              -999              -999          -999          -999          -999          -999
26039  EP192015                 OLAF  20151023  1200             3    15.6N    146.3W           105               957  ...           80          120                45                35                35                45            25            25            20            25

[18295 rows x 22 columns]

In [9]:
#hence we split now for X n Y
train_x = train[prediction_var]
train_y= train['Status']  
print(list(train.columns))
print(train_x.shape)
print(train_y.shape)


['ID', 'Name', 'Date', 'Time', 'Event', 'Status', 'Latitude', 'Longitude', 'Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']
(18295, 14)
(18295,)


In [10]:
test_x= test[prediction_var] 
test_y =test['Status']
print(list(test.columns))
print(test_x.shape)
print(test_y.shape)


['ID', 'Name', 'Date', 'Time', 'Event', 'Status', 'Latitude', 'Longitude', 'Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']
(7842, 14)
(7842,)


In [11]:
#Logistic Regg    
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(train_x, train_y)
log_pred = logmodel.predict(data[prediction_var])
print (log_pred)
print (pd.DataFrame(log_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],log_pred))
print('\nClassification Report')
print(classification_report (data['Status'],log_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],log_pred))
#acc = 0.76
#as we can see only label encoded as 3,4,9,10 can be predicted since once these columns has sufficient data 
#length of confusion matrix is total no. of distinct values in Y(here its 11 so 11x11 confusion matrix is created)

[10 10 10 ...  4  4  4]
        0
0        
3    6647
4    3020
9    5655
10  10815

 Accuracy Score
0.7630179439109309

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.87      0.86      0.86      6766
           4       0.55      0.91      0.69      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.76      0.62      0.68      6965
          10       0.76      0.81      0.78     10076

    accuracy                           0.76     26137
   macro avg       0.27      0.29      0.27     26137
weighted avg       0.76      0.76      0.76     26137

Confusion Matrix
[[   0    0    0    0  217 

In [12]:
data.groupby('Status').agg({'Status': np.size})#we can cross check confusion matrix with this

Status
Status        
0          217
1          152
2          110
3         6766
4         1828
5            6
6            4
7            7
8            6
9         6965
10       10076

In [13]:
# Model KNN  with Euclidian distance  ie P =2 
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 2)
KNN1.fit(train_x,train_y)
KNN1_pred = KNN1.predict(data[prediction_var])
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],KNN1_pred))
print('\nClassification Report')
print(classification_report (data['Status'],KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],KNN1_pred))
#acc = 0.95

[10 10 10 ...  9  4  4]
        0
0        
3    6788
4    1966
9    7227
10  10156

 Accuracy Score
0.9506829398936374

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      0.99      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.93      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

In [14]:
# Model KNN  with N Neighbors = 5 
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier(n_neighbors =5 , metric = 'minkowski', p= 2)
KNN1.fit(train_x,train_y)
KNN1_pred = KNN1.predict(data[prediction_var])
print (KNN1_pred)
print (pd.DataFrame(KNN1_pred).groupby(0).agg({0: np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],KNN1_pred))
print('\nClassification Report')
print(classification_report (data['Status'],KNN1_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],KNN1_pred))
#here even though the acc is similar we get more prediction in diff categories


[10 10 10 ...  9  4  4]
        0
0        
0      44
2      52
3    6777
4    1831
5       2
8       5
9    7249
10  10177

 Accuracy Score
0.9541263343153384

Classification Report
              precision    recall  f1-score   support

           0       0.32      0.06      0.11       217
           1       0.00      0.00      0.00       152
           2       0.33      0.15      0.21       110
           3       1.00      1.00      1.00      6766
           4       0.76      0.76      0.76      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.80      0.67      0.73         6
           9       0.92      0.96      0.94      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.46      0.42      0.43     26137
weighted avg       0.94      0.95      0.95     26137

Conf

In [15]:
# Model KNN with Manhattan Distance ie P =1
from sklearn.neighbors import KNeighborsClassifier
KNN2 = KNeighborsClassifier(n_neighbors =100 , metric = 'minkowski', p= 1)
KNN2.fit(train_x,train_y)
KNN2_pred = KNN2.predict(data[prediction_var])
print (KNN2_pred)
print (pd.DataFrame(KNN2_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],KNN2_pred))
print('\nClassification Report')
print(classification_report (data['Status'],KNN2_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],KNN2_pred))


[10 10 10 ...  9  4  4]
        0
0        
3    6774
4    1956
9    7254
10  10153

 Accuracy Score
0.9522515973524123

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.99      0.99      0.99      6766
           4       0.74      0.79      0.77      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.92      0.96      0.94      6965
          10       0.99      1.00      0.99     10076

    accuracy                           0.95     26137
   macro avg       0.33      0.34      0.34     26137
weighted avg       0.94      0.95      0.94     26137

Confusion Matrix
[[    0     0     0     0  

In [16]:
# Model Naïve Bayes – Gaussian NB 
from sklearn.naive_bayes import GaussianNB
GNB= GaussianNB()
GNB.fit(train_x,train_y)
GNB_pred = GNB.predict(data[prediction_var])
print (GNB_pred)
print (pd.DataFrame(GNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],GNB_pred))
print('\nClassification Report')
print(classification_report (data['Status'],GNB_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],GNB_pred))


[1 1 1 ... 0 0 0]
        0
0        
0    2749
1   19742
3     883
4     605
5     242
6     269
7    1068
8     175
10    404

 Accuracy Score
0.0561655890117458

Classification Report
              precision    recall  f1-score   support

           0       0.08      0.99      0.14       217
           1       0.01      1.00      0.02       152
           2       0.00      0.00      0.00       110
           3       1.00      0.13      0.23      6766
           4       0.00      0.00      0.00      1828
           5       0.01      0.33      0.02         6
           6       0.01      0.50      0.01         4
           7       0.00      0.71      0.01         7
           8       0.03      1.00      0.07         6
           9       0.00      0.00      0.00      6965
          10       0.50      0.02      0.04     10076

    accuracy                           0.06     26137
   macro avg       0.15      0.43      0.05     26137
weighted avg       0.45      0.06      0.08     26137



In [17]:
# Model Naïve Bayes – Bernoulli NB 
from sklearn.naive_bayes import BernoulliNB
BNB = BernoulliNB()
BNB.fit(train_x,train_y)
BNB_pred = BNB.predict(data[prediction_var])
print (BNB_pred)
print (pd.DataFrame(BNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],BNB_pred))
print('\nClassification Report')
print(classification_report (data['Status'],BNB_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],BNB_pred))	


[9 9 9 ... 9 9 9]
        0
0        
3     680
8    1235
9   22770
10   1452

 Accuracy Score
0.32103913991659333

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.03      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      1.00      0.01         6
           9       0.31      1.00      0.47      6965
          10       0.97      0.14      0.24     10076

    accuracy                           0.32     26137
   macro avg       0.12      0.19      0.07     26137
weighted avg       0.46      0.32      0.22     26137

Confusion Matrix
[[   0    0    0    0    0    0 

In [18]:
# Model Naïve Bayes – MultinomialNB 
# (For this algorithm all the x values should be +ve with MinMaxScaler convert all the x values between 0 and 1 )
from sklearn.preprocessing import MinMaxScaler
MMS = MinMaxScaler()
MMS_train_x = MMS.fit_transform(train_x)
MMS_train_y = train_y 

from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(MMS_train_x,MMS_train_y)
MMS_data = MMS.fit_transform (data[prediction_var])
MNB_pred = MNB.predict(MMS_data )
print (MNB_pred)
print (pd.DataFrame(MNB_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],MNB_pred))
print('\nClassification Report')
print(classification_report (data['Status'],MNB_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],MNB_pred))


[10 10 10 ... 10 10 10]
        0
0        
3     870
10  25267

 Accuracy Score
0.4187932815548839

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      0.13      0.23      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.00      0.00      0.00      6965
          10       0.40      1.00      0.57     10076

    accuracy                           0.42     26137
   macro avg       0.13      0.10      0.07     26137
weighted avg       0.41      0.42      0.28     26137

Confusion Matrix
[[    0     0     0     0     0     0     0    

In [24]:
# Model SVM  (Support Vector Machine) Kernel = Sigmoid 
from sklearn.svm import SVC
SVM_SIG = SVC (kernel = 'sigmoid')
SVM_SIG.fit(train_x,train_y)
SVM_SIG_pred = SVM_SIG.predict(data[prediction_var])
print (SVM_SIG_pred)
print (pd.DataFrame(SVM_SIG_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],SVM_SIG_pred))
print('\nClassification Report')
print(classification_report (data['Status'],SVM_SIG_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],SVM_SIG_pred))


[10 10 10 ...  3  3  3]
        0
0        
3    4344
4    2043
9    6946
10  12804

 Accuracy Score
0.2898190304931706

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       0.00      0.00      0.00      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.31      0.31      0.31      6965
          10       0.42      0.54      0.47     10076

    accuracy                           0.29     26137
   macro avg       0.07      0.08      0.07     26137
weighted avg       0.25      0.29      0.27     26137

Confusion Matrix
[[   0    0    0  217    0 

In [25]:
# Model SVM (Support Vector Machine) Kernel = poly (It has performance issue better not to run)
from sklearn.svm import SVC
SVM_POLY = SVC (kernel = 'poly')
SVM_POLY.fit(train_x,train_y)
SVM_POLY_pred = SVM_POLY.predict(data[prediction_var])
print (SVM_POLY_pred)
print (pd.DataFrame(SVM_POLY_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],SVM_POLY_pred))
print('\nClassification Report')
print(classification_report (data['Status'],SVM_POLY_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],SVM_POLY_pred))


[10 10 10 ... 10 10 10]
        0
0        
3    5618
9    7613
10  12906

 Accuracy Score
0.7678004361632934

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       217
           1       0.00      0.00      0.00       152
           2       0.00      0.00      0.00       110
           3       1.00      0.83      0.90      6766
           4       0.00      0.00      0.00      1828
           5       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         7
           8       0.00      0.00      0.00         6
           9       0.77      0.84      0.80      6965
          10       0.67      0.86      0.75     10076

    accuracy                           0.77     26137
   macro avg       0.22      0.23      0.22     26137
weighted avg       0.72      0.77      0.74     26137

Confusion Matrix
[[   0    0    0    0    0    0    0 

In [ ]:
# Model SVM  (Support Vector Machine) Kernel = Linear
from sklearn.svm import SVC
SVM_LIN = SVC (kernel = 'linear')
SVM_LIN.fit(train_x,train_y)
SVM_LIN_pred = SVM_LIN.predict(data[prediction_var])
print (SVM_LIN_pred)
print (pd.DataFrame(SVM_LIN_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],SVM_LIN_pred))
print('\nClassification Report')
print(classification_report (data['Status'],SVM_LIN_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],SVM_LIN_pred))


In [ ]:
# Model SVM  (Support Vector Machine) Kernel = rbf 
from sklearn.svm import SVC
SVM_RBF = SVC (kernel = 'rbf')
SVM_RBF.fit(train_x,train_y)
SVM_RBF_pred = SVM_RBF.predict(data[prediction_var])
print (SVM_RBF_pred)
print (pd.DataFrame(SVM_RBF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],SVM_RBF_pred))
print('\nClassification Report')
print(classification_report (data['Status'],SVM_RBF_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],SVM_RBF_pred))


In [26]:
# Model Decision Tree with criterion = 'entropy' 
from sklearn.tree import DecisionTreeClassifier
TREE = DecisionTreeClassifier (criterion = 'entropy')
TREE.fit(train_x,train_y)
TREE_pred = TREE.predict(data[prediction_var])
print (TREE_pred)
print (pd.DataFrame(TREE_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],TREE_pred))
print('\nClassification Report')
print(classification_report (data['Status'],TREE_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],TREE_pred))


[10 10 10 ...  9  4  4]
        0
0        
0      15
2      33
3    6783
4    2079
5       2
7       4
8       6
9    7088
10  10127

 Accuracy Score
0.9589088265677009

Classification Report
              precision    recall  f1-score   support

           0       0.47      0.03      0.06       217
           1       0.00      0.00      0.00       152
           2       0.76      0.23      0.35       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.75      0.43      0.55         7
           8       1.00      1.00      1.00         6
           9       0.94      0.95      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.70      0.53      0.56     26137
weighted avg       0.95      0.96      0.95     2

In [27]:
# Model Decision Tree with criterion = 'gini' 
from sklearn.tree import DecisionTreeClassifier
TREE_GINI = DecisionTreeClassifier (criterion = 'gini')
TREE_GINI.fit(train_x,train_y)
TREE_GINI_pred = TREE_GINI.predict(data[prediction_var])
print (TREE_GINI_pred)
print (pd.DataFrame(TREE_GINI_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],TREE_GINI_pred))
print('\nClassification Report')
print(classification_report (data['Status'],TREE_GINI_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],TREE_GINI_pred))


[10 10 10 ...  9  4  4]
        0
0        
0      15
2      33
3    6783
4    2078
5       2
7       4
8       6
9    7088
10  10128

 Accuracy Score
0.9589470865057199

Classification Report
              precision    recall  f1-score   support

           0       0.47      0.03      0.06       217
           1       0.00      0.00      0.00       152
           2       0.76      0.23      0.35       110
           3       1.00      1.00      1.00      6766
           4       0.74      0.85      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       0.75      0.43      0.55         7
           8       1.00      1.00      1.00         6
           9       0.94      0.95      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.70      0.53      0.56     26137
weighted avg       0.95      0.96      0.95     2

In [28]:
# Model Random Forest with criterion = 'entropy' 
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='entropy')
RF.fit(train_x,train_y)
RF_pred = RF.predict(data[prediction_var])
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],RF_pred))
print('\nClassification Report')
print(classification_report (data['Status'],RF_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],RF_pred))
#best One Yet

[10 10 10 ...  9  4  4]
        0
0        
0      11
2      32
3    6784
4    2054
5       2
7       2
8       6
9    7107
10  10139

 Accuracy Score
0.9591001262577955

Classification Report
              precision    recall  f1-score   support

           0       0.45      0.02      0.04       217
           1       0.00      0.00      0.00       152
           2       0.75      0.22      0.34       110
           3       1.00      1.00      1.00      6766
           4       0.75      0.84      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       1.00      0.29      0.44         7
           8       1.00      1.00      1.00         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.72      0.51      0.55     26137
weighted avg       0.95      0.96      0.95     2

In [29]:
# Model Random Forest with criterion = 'gini' 
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=100, criterion='gini')
RF.fit(train_x,train_y)
RF_pred = RF.predict(data[prediction_var])
print (RF_pred)
print (pd.DataFrame(RF_pred).groupby(0).agg({0:np.size}))
print('\n Accuracy Score')
print (accuracy_score (data['Status'],RF_pred))
print('\nClassification Report')
print(classification_report (data['Status'],RF_pred))
print('Confusion Matrix')
print (confusion_matrix (data['Status'],RF_pred))


[10 10 10 ...  9  4  4]
        0
0        
0      15
2      23
3    6784
4    2064
5       2
7       2
8       6
9    7105
10  10136

 Accuracy Score
0.9591383861958144

Classification Report
              precision    recall  f1-score   support

           0       0.47      0.03      0.06       217
           1       0.00      0.00      0.00       152
           2       0.91      0.19      0.32       110
           3       1.00      1.00      1.00      6766
           4       0.75      0.84      0.79      1828
           5       1.00      0.33      0.50         6
           6       0.00      0.00      0.00         4
           7       1.00      0.29      0.44         7
           8       1.00      1.00      1.00         6
           9       0.94      0.96      0.95      6965
          10       0.99      1.00      1.00     10076

    accuracy                           0.96     26137
   macro avg       0.73      0.51      0.55     26137
weighted avg       0.95      0.96      0.95     2